# Copyright 2016 Google Inc. All Rights Reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
FROM ubuntu:16.04
MAINTAINER kcc@google.com
RUN apt-get update && apt-get upgrade -y && apt-get autoremove -y
RUN apt-get install -y git sudo
