FROM gcr.io/fuzzer-test-suite/gcloud-clang-deps

# Create directory, and set it as the working directory "."
WORKDIR /work
# Add files from "real" filesystem to the container's
COPY . .
# Set env var
ENV WORK /work
